name: test CI/CD Pipeline

on:
  push:
    branches: ['*']

jobs:
  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to test server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ vars.PORT }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ vars.PROXY_USERNAME }}
          proxy_key: ${{ secrets.KEY }}
          proxy_port: ${{ vars.PROXY_PORT }}
          script: |
            hostname -I
            date
            ls -la